# Generated by Django 3.0.5 on 2020-05-02 13:03

from django.db import migrations

def create_data(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    for i in range(100):
        title = 'Lorem ipsum {0}'.format(i)
        Article.objects.create(title=title, excerpt='Lorem ipsum dolor sit amet', body='Lorem ipsum dolor sit amet, consectetur adipiscing elit.')

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
